### ISSUE TITLE
リポジトリのファイル構成を変更

### ISSUE THREAD

**Issue by shymst** [Chino-s/travel_c#10]
# 概要
リポジトリのルートディレクトリにある`patchwork`は要りません。
以下のようにリポジトリ直下がプロジェクトルートの直下になるようにしてください。

**現在**
```
patchwork
rails
└ travel_c
        ├ app
        ├ config
        ├ db
         ...
```

**変更後** 
```
app
config
db
...
```

**Comment by Chino-s** [comment]
すみません。エビデンスする前にpushしてしまったので、
ここにシュクショを貼らせていただきます。
<img width="1440" alt="2017-05-26 14 17 56" src="https://cloud.githubusercontent.com/assets/28725380/26481813/7c925f2a-421e-11e7-80a2-e66ec1b28c94.png">
