### ISSUE TITLE
.DS_Storeをgitで管理しないように変更

### ISSUE THREAD

**Issue by shymst** [Chino-s/travel_c#11]
# 概要
`.gitignore` を編集して gitで `.DS_Store`を管理しないようにしてください。

更に以下の質問をコメント欄で説明してください。
- [x]  `.gitignore`とは何か?
- [x] `.DS_Store`とは何か?

**Comment by Chino-s** [comment]
# .gitignoreとは何か?
.gitignoreとは、Gitリポジトリにおいて、意図的に追跡対象から外したい（無視したい）ファイル(Git の管理に含めないファイル)を設定するためのファイル

# .DS_Storeとは何か
OS Xで作成された独自の形式の隠しファイル。 
アイコンの位置や表示設定などのフォルダ表示設定に関するメタデータを記録するための隠しファイルである。Finder上でもリモートシステム上でもアクセスするすべてのフォルダに.DS_Storeファイルが生成されてしまう。

削除する際、
.DS_StoreはMacからWindowsへファイルを渡したりする場合には不要となるので、.DS_Storeは削除しておきたいが、.DS_Storeを削除するとフォルダ内のアイコン表示位置がリセットされたり、spotlightのコメントが削除されたりするから注意。

**Comment by shymst** [comment]
OKです
