### ISSUE TITLE
使用するDBをMysqlにする

### ISSUE THREAD

**Issue by Chino-s** [Chino-s/travel_c#12]
## 前提

山本の指示ミスで使用するDBを指定するのを忘れていて
参考書通りに進めていたため'SQLite'で実装を進めていたことが判明・・・。

## 要件

以下のサイトを参考に使用しているDBを`SQLite`から`MySQL`に変更すること

```
http://qiita.com/pchatsu/items/a7f53da2e57ae4aca065
```
## 備考

エビデンス（証跡）としてプルリクエストには'migrate'を流したあとの
テーブル情報のログと

国一覧ページが正しく動作していることがわかるキャプチャを貼り付けること

**Comment by Chino-s** [comment]
# memo

以下のエラーが出て、起動しなかった

```
$ sudo mysql.server start
Starting MySQL
. ERROR! The server quit without updating PID file (/usr/local/var/mysql/SakuraMBP.local.pid).
```
山本さんが以下の記事で解決！
http://qiita.com/gaogaomango/items/933a1f55004920a4323d

**Comment by Chino-s** [comment]
帰社のタイミングで作業

**Comment by takumiyamamoto** [comment]
@Chino-s @shymst 

山下からアドバイスがあったので
dockerで構築した環境を茅野に展開する形にする

初Dockerなので展開できるようになるまでMySQLに移行するのはpending
