### ISSUE TITLE
Railsコマンドで自動作成されたが使用していない不要なファイルを削除する

### ISSUE THREAD

**Issue by takumiyamamoto** [Chino-s/travel_c#14]
## 前提

#10 のフォルダ構成変更に伴い
ついでに現時点では不要なファイルは存在していても無駄なため一旦、整理したい

## 要件

以下に従いファイルを削除する

* 'test'
  * testディレクトリ丸ごと削除する
* 'app/helpers'
  * 'application_helper.rb'以外の使用していないファイル
* 'app/controllers'
  * 'application_controllers'以外の使用していないファイル
* 'app/models'
  * 使用していないファイル
* 'app/controllers'
  * 使用していないファイル

* その他
  * 一旦やり直すために[#2]で追加してしまった内容についてもこのissueで削除すること

## 備考

プルリクエストには削除後も画面が正しく表示できる証拠に画面のキャプチャ等を
貼り付けておくこと

**Comment by Chino-s** [comment]
# 不要なファイルを削除

削除完了。また、画面も正しく表示されている。
[#2]での追加内容も削除完了。

<img width="1440" alt="2017-05-29 14 08 55" src="https://cloud.githubusercontent.com/assets/28725380/26537279/f2e9a8de-4478-11e7-8bc6-939f9f1eeb80.png">
<img width="1440" alt="2017-05-29 14 08 59" src="https://cloud.githubusercontent.com/assets/28725380/26537280/f40e32b6-4478-11e7-8a0a-8a0f67995d76.png">
<img width="1440" alt="2017-05-29 14 09 03" src="https://cloud.githubusercontent.com/assets/28725380/26537282/fbb7a9de-4478-11e7-8995-9f93fa1bfbbd.png">
<img width="1440" alt="2017-05-29 14 09 25" src="https://cloud.githubusercontent.com/assets/28725380/26537283/fe1f9eca-4478-11e7-81a7-df77beba58d1.png">

**Comment by takumiyamamoto** [comment]
@Chino-s プルリクエストは作るようにしてね
